name: Gitee repos mirror periodic job

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Mirror the Github organization repos to Gitee
    - name: Mirror the Github organization repos to Gitee
      uses: Yikun/gitee-mirror-action@v0.10
      with:
        src: github/jjcszxh
        dst: gitee/jjcszxh
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        static_list: "docker_installer"

    - name: Download GitHub Release Assets
      run: |
        # 使用 GitHub API 获取仓库的 Releases 文件
        curl -s "https://api.github.com/repos/github/jjcszxh/releases/latest" | jq -r '.assets[].browser_download_url' | while read url; do
          # 下载文件
          curl -LO "$url"
        done

    - name: Upload Release Files to Gitee
      run: |
        # 将下载的文件推送到 Gitee 仓库
        git config --global user.name "your_username"
        git config --global user.email "your_email"
        git clone https://gitee.com/${{ secrets.GITEE_USERNAME }}/jjcszxh.git
        cd jjcszxh
        # 假设你已经下载了发行版文件到当前目录
        mv ../*.tar.gz .  # 或者适应你的文件格式
        git add .
        git commit -m "Add release files"
        git push origin master
